REFERENCE_SEQUENCE = [
    {"page": 1, "kind": "cover", "title": "ALORUH"},
    {"page": 2, "kind": "divider", "section": "brand_positioning", "title": "Visual Positioning Calibration"},
    {"page": 3, "kind": "store_profile", "section": "brand_positioning", "title": "店铺基本信息", "subtitle": "数据范围与采集边界"},
    {"page": 4, "kind": "category_overview", "section": "brand_positioning", "title": "重点品类", "subtitle": "全量商品结构决定优先分析范围"},
    {"page": 5, "kind": "style_split", "section": "brand_positioning", "title": "重点品类与风格划分", "subtitle": "数据库全量标签分布 + GPT-5.6 Sol 随机样本复核"},
    {"page": 6, "kind": "mosaic", "section": "brand_positioning", "claim": 2, "title": "CURRENT VISUAL ASSETS", "subtitle": "当前用户感知"},
    {"page": 7, "kind": "divider", "section": "product_display", "title": "PRODUCT DISPLAY ANALYSIS"},
    {"page": 8, "kind": "scope", "section": "product_display", "claim": 0, "title": "不是缺少好图，而是缺少可复制的图法系统"},
    {"page": 9, "kind": "category_sample", "section": "product_display", "claim": 0, "category_index": 0, "title": "重点品类随机样本 01"},
    {"page": 10, "kind": "category_sample", "section": "product_display", "claim": 1, "category_index": 1, "title": "重点品类随机样本 02"},
    {"page": 11, "kind": "category_sample", "section": "product_display", "claim": 2, "category_index": 2, "title": "重点品类随机样本 03"},
    {"page": 12, "kind": "method", "section": "product_display", "title": "分析口径：不同画面回答不同问题"},
    {"page": 13, "kind": "feature", "section": "product_display", "claim": 1, "title": "重点提升款：商品有吸引力，首图信息仍不足"},
    {"page": 14, "kind": "matrix", "section": "product_display", "claim": 2, "title": "每个品类固定 构图 - 动作 - 卖点 - 场景"},
    {"page": 15, "kind": "divider", "section": "store_visual_audit", "title": "STORE VISUAL AUDIT"},
    {"page": 16, "kind": "logic", "section": "store_visual_audit", "claim": 0, "title": "Store Display Logic"},
    {"page": 17, "kind": "mosaic", "section": "store_visual_audit", "claim": 0, "title": "摄影视觉风格", "subtitle": "场景层级尚未统一"},
    {"page": 18, "kind": "quote", "section": "store_visual_audit", "claim": 0, "title": "Clarify occasions, strengthen hero images, and improve browsing efficiency."},
    {"page": 19, "kind": "mosaic", "section": "store_visual_audit", "claim": 1, "title": "摄影视觉风格", "subtitle": "同场景同动作重复"},
    {"page": 20, "kind": "mosaic", "section": "store_visual_audit", "claim": 2, "title": "摄影视觉风格", "subtitle": "文字、模板与水印失序"},
    {"page": 21, "kind": "quote", "section": "store_visual_audit", "claim": 1, "title": "统一场景入口，强化首图吸引力，提升店铺浏览效率。"},
    {"page": 22, "kind": "dense_mosaic", "section": "store_visual_audit", "claim": 0, "title": "First Image Types", "subtitle": "当前首图类型汇总"},
    {"page": 23, "kind": "three_compare", "section": "store_visual_audit", "claim": 1, "title": "First Image Types", "subtitle": "动作表达叙事不统一"},
    {"page": 24, "kind": "model_portrait", "section": "store_visual_audit", "claim": 1, "title": "可见模特画像", "subtitle": "只记录画面可见、非敏感属性"},
    {"page": 25, "kind": "three_compare", "section": "store_visual_audit", "claim": 2, "title": "Fabric details & icons", "subtitle": "面料细节及功能信息展示"},
    {"page": 26, "kind": "divider", "section": "competitive_gap", "title": "Visual Discrepancy Breakdown"},
    {"page": 27, "kind": "brand_codes", "section": "competitive_gap", "title": "BRAND VISUAL CODES", "subtitle": "竞品视觉语言差异"},
    {"page": 28, "kind": "brand_feature", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "PRINCESS POLLY", "subtitle": "干净电商骨架 + 编辑与生活方式弹性"},
    {"page": 29, "kind": "dense_mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "PRINCESS POLLY", "subtitle": "规模化首图系统"},
    {"page": 30, "kind": "mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "视觉基调：网感与商品可读性平衡", "subtitle": "Visual tone"},
    {"page": 31, "kind": "dense_mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "Model Faces", "subtitle": "模特面孔"},
    {"page": 32, "kind": "mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "DAILY 视觉语言", "subtitle": "Model States · DAILY"},
    {"page": 33, "kind": "mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "PARTY 视觉语言", "subtitle": "Model States · PARTY"},
    {"page": 34, "kind": "mosaic", "section": "competitive_gap", "claim": 0, "store": "princess_polly", "title": "BEACH / VACATION 视觉语言", "subtitle": "Model States · BEACH"},
    {"page": 35, "kind": "brand_feature", "section": "competitive_gap", "claim": 1, "store": "motel", "title": "MOTEL ROCKS", "subtitle": "高度标准化的中性棚拍体系"},
    {"page": 36, "kind": "mosaic", "section": "competitive_gap", "claim": 1, "store": "motel", "title": "视觉基调：标准化商品摄影", "subtitle": "Visual tone"},
    {"page": 37, "kind": "brand_feature", "section": "competitive_gap", "claim": 2, "store": "prettylittlething", "title": "PRETTYLITTLETHING", "subtitle": "规模化一致性"},
    {"page": 38, "kind": "mosaic", "section": "competitive_gap", "claim": 2, "store": "prettylittlething", "title": "视觉基调：按品类固定构图", "subtitle": "Visual tone"},
    {"page": 39, "kind": "roadmap", "section": "competitive_gap", "title": "从单张好图升级为分品类主图模板"},
    {"page": 40, "kind": "divider", "section": "visual_upgrade", "title": "VISUAL UPGRADE DIRECTION"},
    {"page": 41, "kind": "brand_feature", "section": "visual_upgrade", "claim": 0, "title": "STANDARDIZED TRY-ON", "subtitle": "标准商品层 + 品牌氛围层"},
    {"page": 42, "kind": "dense_mosaic", "section": "visual_upgrade", "claim": 0, "title": "ALORUH 视觉系列画像", "subtitle": "出门前的轻性感状态"},
    {"page": 43, "kind": "quote", "section": "visual_upgrade", "claim": 0, "title": "从 拍商品 转向 追趋势、做搭配、造氛围"},
    {"page": 44, "kind": "four_series", "section": "visual_upgrade", "claim": 0, "title": "3-1 系列线视觉规划", "subtitle": "VISUAL SERIES"},
    {"page": 45, "kind": "mosaic", "section": "visual_upgrade", "claim": 3, "title": "现有休闲货盘风貌", "subtitle": "有网感，但缺少统一光线、构图与模特状态"},
    {"page": 46, "kind": "mosaic", "section": "visual_upgrade", "claim": 2, "title": "visual tone", "subtitle": "浅暖灰底、统一色温与固定品牌组件"},
    {"page": 47, "kind": "flow", "section": "visual_upgrade", "claim": 3, "title": "用趋势搭配带动氛围首图点击"},
    {"page": 48, "kind": "three_compare", "section": "visual_upgrade", "claim": 0, "title": "网感首图优化对比", "subtitle": "现状 -> 标准商品图 -> 氛围图"},
    {"page": 49, "kind": "four_compare", "section": "visual_upgrade", "claim": 3, "title": "搭配调整对比", "subtitle": "固定规则，不固定遮挡动作"},
    {"page": 50, "kind": "grid_compare", "section": "visual_upgrade", "claim": 0, "title": "BEFORE"},
    {"page": 51, "kind": "grid_compare", "section": "visual_upgrade", "claim": 1, "title": "REFERENCE"},
    {"page": 52, "kind": "plan", "section": "visual_upgrade", "claim": 2, "title": "PLAN A", "subtitle": "统一商品信息层"},
    {"page": 53, "kind": "plan", "section": "visual_upgrade", "claim": 3, "title": "PLAN B", "subtitle": "统一品牌氛围层"},
]

SECTION_PAGE_ORDER = [
    (2, "brand_positioning"),
    (7, "product_display"),
    (15, "store_visual_audit"),
    (26, "competitive_gap"),
    (40, "visual_upgrade"),
]
